import type { Metadata } from "next";

import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
    {/* <SidebarProvider> */}
     
        {/* <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-500 flex items-start justify-between`}
        > */}
          {/* <Sidebar/> */}
          <body>
          <main >
          {/* <AppSidebar /> */}
              {children}
            
          </main>
          </body>

        {/* </body> */}
     
    {/* </SidebarProvider> */}
    </html>
  );
}
